/** @type {import('tailwindcss').Config} */
// Design tokens extracted verbatim from the Stitch "Lumina Editorial"
// design system (DESIGN.md) and the exported screen code.html files.
// DO NOT change these values without updating the source design system.
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-surface': '#2f3131',
        'on-error': '#ffffff',
        tertiary: '#555f6f',
        'surface-container-highest': '#e2e2e2',
        'secondary-container': '#bae6fd',
        outline: '#7a7583',
        'on-primary-fixed': '#21005e',
        'surface-variant': '#e2e2e2',
        'on-secondary': '#ffffff',
        'primary-fixed-dim': '#cebdff',
        'secondary-fixed-dim': '#a1cde3',
        'error-container': '#ffdad6',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed-variant': '#3d4756',
        'on-tertiary-container': '#2b3543',
        'tertiary-fixed-dim': '#bdc7d9',
        'on-surface-variant': '#494552',
        'on-primary-fixed-variant': '#4f319c',
        'on-background': '#1a1c1c',
        'primary-fixed': '#e8ddff',
        'surface-bright': '#f9f9f9',
        secondary: '#396477',
        'surface-container-low': '#f3f3f4',
        'on-secondary-fixed-variant': '#1e4c5f',
        'inverse-on-surface': '#f0f1f1',
        'tertiary-fixed': '#d9e3f6',
        surface: '#f9f9f9',
        'on-primary-container': '#3c1989',
        'tertiary-container': '#939daf',
        primary: '#674bb5',
        'on-surface': '#1a1c1c',
        'surface-container': '#eeeeee',
        background: '#f9f9f9',
        'on-secondary-fixed': '#001f2a',
        'secondary-fixed': '#bee9ff',
        'surface-dim': '#dadada',
        error: '#ba1a1a',
        'inverse-primary': '#cebdff',
        'on-tertiary-fixed': '#121c2a',
        'on-error-container': '#93000a',
        'primary-container': '#a78bfa',
        'surface-tint': '#674bb5',
        'outline-variant': '#cac4d4',
        'on-tertiary': '#ffffff',
        'on-primary': '#ffffff',
        'surface-container-high': '#e8e8e8',
        'on-secondary-container': '#3d687c',
      },
      borderRadius: {
        sm: '0.5rem',
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'container-padding-mobile': '20px',
        'container-padding-desktop': '40px',
        gutter: '24px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
      },
      fontFamily: {
        'title-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
      boxShadow: {
        'glass-light': '0px 10px 30px rgba(0, 0, 0, 0.04)',
        'glass-dark': '0px 10px 40px rgba(0, 0, 0, 0.2)',
        'button-glow': '0 0 20px rgba(103, 75, 181, 0.3)',
      },
    },
  },
  plugins: [],
};
